name: 전자정보프레임워크 사용하여 빌드 및 배포

on:
  push:
    branches:
      - main  # 주석 : main 브랜치에 push가 되면 actions가 동작함.

jobs:
  build:
    runs-on: ubuntu-24.04  # 어떤 운영체제 버전에서 실행하는지 설정.

    steps:
    - name: source check out
      uses: actions/checkout@v3

    - name: maven build
      run: mvn clean package
