name: 전자정부프레엠웍을 사용하여 빌드 및 배포

on:
  push:
    branches:
      - main      # 주석 : main 브랜치에 push가 되면 actions가 동작함

jobs:
  build:
    runs-on: ubuntu-latest  # 어떤 운영체제 버전에서 실행하는지 설정 cancel-timeout-minutes: cancel-timeout-minutes: 

    steps:
    
    # 1. GitHub 저장소의 소스코드 가져오기
    - name: 소스 check out 
      uses: actions/checkout@v3
    
    # 2. Maven으로 WAR 파일 생성
    - name: 메이븐 빌드
      run: mvn clean package -DskipTests
    
    # 3. Docker 이미지 생성
    - name: Build Docker Image
      run: |
        docker build \
          -t ${{ secrets.DOCKERHUB_ID }}/hello:latest \
          .

    # 4. Docker Hub 로그인
    - name: Login to Docker Hub
      uses: docker/login-action@v4
      with:
        username: ${{ secrets.DOCKERHUB_ID }}
        password: ${{ secrets.DOCKERHUB_PW }}
        
    # 5. Docker Hub에 이미지 업로드
    - name: Push Docker Image
      run: |
        docker push \
          ${{ secrets.DOCKERHUB_ID }}/hello:latest
          
    # 6. EC2 접속 후 컨테이너 배포
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.2.5
      with:
        host: 15.164.212.51
        username: ubuntu
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          docker pull ${{ secrets.DOCKERHUB_ID }}/hello:latest

          docker stop hello || true
          docker rm hello || true

          docker run -d \
            --name hello \
            -p 8080:8080 \
            ${{ secrets.DOCKERHUB_ID }}/hello:latest
