name: 전자정보프레임워크 사용하여 빌드 및 배포

on:
  push:
    branches:
      - main  # 주석 : main 브랜치에 push가 되면 actions가 동작함.

jobs:
  build:
    runs-on: ubuntu-24.04  # 어떤 운영체제 버전에서 실행하는지 설정.

    steps:
    - name: git 저장소 소스 복사 전의 폴더 구조
      run: ls -la
    
    - name: source check out
      uses: actions/checkout@v3
      
    - name: git 저장소 소스 복사 후의 폴더 구조
      run: ls -la
      
    - name: git 저장소 소스 복사 후의 hello 폴더 구조
            # 리눅스 쉘 명령어 2줄 이상 실행시
      run: | 
        ls -la
        
    - name: maven build
      run: mvn clean package
      
    - name: 보안 환경변수를 이용하여 개인키 파일 생성
      run: | 
        mkdir -p ~/.ssh
        echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_ras
        chmod 600 ~/.ssh/id_ras
        
    - name: actions을 사용하여 보안 환경변수를 이용하여 개인키 파일 생성
      uses: webfactiory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}
        
    - name: 서버 연결시 지문 등록
      run: ssh-keyscan -t ed25519 3.35.22.125 >> ~/.ssh/known_host
      
    - name: 개인키 파일 확인
      run: |
        cat ~/.ssh/id_rsa
        cat ~/.ssh/known_hosts
        
        
    